<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="design" content="WeGo">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="css/style2.css">
<title>weGo</title>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
<body>
<div class="grid-container">
<!--header -->
  <div class="item1">


    <!--search bar-->
    <!--site title -->
  <center>
  <div class="Hdiv">
  <center><h1>WeGo </h1></center>
  <center><h5>buy your sports equipment safely</h5></center>
  <center>
			<p>“In sport, as soon as you stop, you regress.” <p/></center>
 </div>
 </center>
  </div>
 <!--Menu --> 
  <div class="item2">
  <nav>
	<ul>
		  <li><a href="#home">Home</a></li>
		  <li><a href="#news">News</a></li>
		  <li><a href="#contact">Contact</a></li>
       <li><a href="#contact">Your Account</a></li>
		  <li style="float:right"><a class="active" href="#about">About</a></li>
     </ul>
 
  </div>
 <!--Main --> 
  <div class="item3">
  <div class="fdiv">
  <form action="/action_page.php">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>
    <label for="email">Email</label>
    <input type="text" id="email" name="email" placeholder="xxxx.xx@xx.xx">
     <label for="pw">Password</label>
    <input type="password" id="pw" name="pw" placeholder="Your password ....">
  
    <input type="submit" value="Submit">
  </form>
</div>
  
  
  </div>  
  <div class="item4">
  
  </div>
  
  
  
<!--footer -->
  <div class="item5">
  <footer>
     <div class="reseauxsociaux">
		<a href="" class="fab fa-instagram"></a>
		<a href="" class="fab fa-facebook-f"></a>
		<a href="" class="fab fa-youtube"></a>
		<a href="" class="fa fa-rss"></a>
	</div>
  </footer>
  </div>
</div>
</body>
</html>