<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="design" content="WeGo">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="css/style.css">
<title>weGo</title>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
<body>
<header>
<div class="div1">
<center>
	<table>
	<thead>
	<tr>
		<th colspan="2">
			<center><h1>WeGo </h1></center>
			<center><h5>buy your sports equipment safely</h5></center>
		</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td colspan="2">
			<center><p>“Sport entertains the masses, eats their minds and dumbs them down.”</p>
			<p>“In sport, as soon as you stop, you regress.” <p/></center>
		</td>	
	</tr>
	</tbody>
	</table>
	</center>
</div>
<nav>
		<ul class="container">
			<li><a href="administration.php"><i class="fas fa-cogs"></i>SHOP</a></li>
			<li><a href="index.php"><i class="fas fa-home"></i> HOME </a></li>
			<li><a href="index.php"><i class="fas fa-home"></i> CONTACT</a></li>
		    <li><a href="administration.php"><i class="fas fa-sign-out-alt"></i> leave </a></li>
		</ul>
		
		</nav>
</header>
<nav>

</nav>
<div class="milieu">
	<!--la partie dynamique 
	<?php require $template.".phtml" ?>-->
</div>
<footer>
<div class="design">
	<strong>VOILA VOILA POTOO!!</strong>
	<div class="reseauxsociaux">
		<a href="" class="fab fa-instagram"></a>
		<a href="" class="fab fa-facebook-f"></a>
		<a href="" class="fab fa-youtube"></a>
		<a href="" class="fa fa-rss"></a>
	</div>
	</footer>
	<!--  <script type="text/javascript" src="js/script.js"></script>-->
	</body>
	</html>